SAMPLE_RATE=48000
CAPTURE_CHUNK_SIZE=64
PLAYBACK_CHUNK_SIZE=64
CORRELATION_WINDOW_SIZE=1024
CORRELATION_WINDOW_SIZE_MS=$(python3 -c "print(1000.0*$CORRELATION_WINDOW_SIZE/$SAMPLE_RATE);")
CORRELATION_WINDOW_STEP_FACTOR=4
CORRELATION_WINDOW_STEP_SIZE_MS=$(python3 -c "print($CORRELATION_WINDOW_SIZE_MS/$CORRELATION_WINDOW_STEP_FACTOR);")

event_logging=false
mic_audio_recording=false
feed_realtime_factor=10000

