SAMPLE_RATE=48000
CAPTURE_CHUNK_SIZE=64
PLAYBACK_CHUNK_SIZE=64
ENERGY_WINDOW_SIZE=1024
ENERGY_WINDOW_SIZE_MS=$(python3 -c "print(1000.0*$ENERGY_WINDOW_SIZE/$SAMPLE_RATE);")
echo Energy window size $ENERGY_WINDOW_SIZE_MS ms
ENERGY_WINDOW_STEP_FACTOR=4
ENERGY_WINDOW_STEP_SIZE_MS=$(python3 -c "print($ENERGY_WINDOW_SIZE_MS/$ENERGY_WINDOW_STEP_FACTOR);")
echo Energy window step size $ENERGY_WINDOW_STEP_SIZE_MS ms

event_logging=false
mic_audio_recording=false
feed_realtime_factor=10000

